<<<<<<< HEAD
// generated by ./configure 
// CXXAUTOFLAGS=" -march=native" 
=======
// generated by ./configure 
// CXXAUTOFLAGS=" -march=native" 
>>>>>>> 3c6e9e06 (Merge pull request #9 from eshf/norieworks)
